language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
  - python get-poetry.py --version 1.0.0b2 --yes
install:
  - ~/.poetry/bin/poetry install
  - pip uninstall pytest-serverless --yes
  - ~/.poetry/bin/poetry run pip install pytest==$PYTEST_VERSION
script:
  - ~/.poetry/bin/poetry run pytest
env:
  - PYTEST_VERSION=3.10.1
  - PYTEST_VERSION=4.6.6
  - PYTEST_VERSION=5.2.4
